name: Publish articles

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_articles:
    runs-on: ubuntu-latest
    environment: publish
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT_CHECKOUT }}
          fetch-depth: 0
      - run: qiita publish --all
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
      - run: |
          git add ./public/*
          if ! git diff --staged --exit-code --quiet; then
            git commit -m 'Updated by qiita-cli'
            git push --force
          fi
